const express = require('express');
const crypto = require('crypto');
const webpush = require('web-push');
const { createClient } = require('@supabase/supabase-js');

const app = express();
app.use(express.json({limit:'2mb'}));
const supabaseUrl = process.env.SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!supabaseUrl || !serviceKey) console.warn('Supabase environment variables are missing.');
const db = createClient(supabaseUrl || 'https://example.supabase.co', serviceKey || 'missing');
const now=()=>new Date().toISOString();
const uid=(prefix)=>`${prefix}-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;
const admin=(req,res,next)=>{ if(!process.env.ADMIN_PIN || req.headers['x-admin-pin']!==process.env.ADMIN_PIN) return res.status(401).json({error:'Admin PIN required'}); next(); };
const q=async (table)=>{const {data,error}=await db.from(table).select('*');if(error)throw error;return data||[]};

app.get('/api/settings',async(req,res)=>{try{const rows=await q('settings');const out={};rows.forEach(r=>out[r.k]=r.v);res.json(out)}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/settings',admin,async(req,res)=>{try{for(const [k,v] of Object.entries(req.body||{})){const {error}=await db.from('settings').upsert({k,v:String(v??'')},{onConflict:'k'});if(error)throw error}res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/members',async(req,res)=>{try{const {data,error}=await db.from('members').select('*').order('created_at',{ascending:false});if(error)throw error;res.json(data||[])}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/members',async(req,res)=>{try{const b=req.body||{};if(!b.name)return res.status(400).json({error:'नाव आवश्यक आहे'});const id=uid('SRP-M');const {error}=await db.from('members').insert({id,name:b.name,mobile:b.mobile||'',email:b.email||'',address:b.address||'',role:b.role||'सदस्य',area:b.area||'',photo:b.photo||'',created_at:now()});if(error)throw error;res.json({ok:true,id})}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/members/:id',admin,async(req,res)=>{try{const b=req.body||{};const {error}=await db.from('members').update({name:b.name,mobile:b.mobile||'',email:b.email||'',address:b.address||'',role:b.role||'सदस्य',area:b.area||'',photo:b.photo||''}).eq('id',req.params.id);if(error)throw error;res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/members/:id',async(req,res)=>{try{const {data,error}=await db.from('members').select('*').eq('id',req.params.id).maybeSingle();if(error)throw error;if(!data)return res.status(404).json({error:'सदस्य सापडला नाही'});res.json(data)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/receipts',async(req,res)=>{try{const {data,error}=await db.from('receipts').select('*').order('created_at',{ascending:false});if(error)throw error;res.json(data||[])}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/receipts',async(req,res)=>{try{const b=req.body||{};if(!b.name||!b.amount)return res.status(400).json({error:'नाव आणि रक्कम आवश्यक आहे'});const id=uid('SRP-R');const {error}=await db.from('receipts').insert({id,name:b.name,mobile:b.mobile||'',address:b.address||'',amount:Number(b.amount),payment:b.payment||'रोख',amount_words:b.amount_words||'',note:b.note||'',created_at:now(),member_id:b.member_id||''});if(error)throw error;res.json({ok:true,id})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/aarti/today',async(req,res)=>{try{const d=new Date().toISOString().slice(0,10);const {data,error}=await db.from('aarti').select('*').eq('date',d).order('id',{ascending:true}).limit(1).maybeSingle();if(error)throw error;res.json(data||null)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/aarti',async(req,res)=>{try{const {data,error}=await db.from('aarti').select('*').order('date',{ascending:true}).order('time',{ascending:true});if(error)throw error;res.json(data||[])}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/aarti',admin,async(req,res)=>{try{const b=req.body||{};const {error}=await db.from('aarti').insert({date:b.date,time:b.time||'',member_id:b.member_id||'',member_name:b.member_name||'',notes:b.notes||''});if(error)throw error;res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/aarti/:id',admin,async(req,res)=>{try{const {error}=await db.from('aarti').delete().eq('id',req.params.id);if(error)throw error;res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/notifications',async(req,res)=>{try{const {data,error}=await db.from('notifications').select('*').order('id',{ascending:false}).limit(100);if(error)throw error;res.json(data||[])}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/notifications',admin,async(req,res)=>{try{const b=req.body||{};if(!b.title||!b.message)return res.status(400).json({error:'Title/message required'});const {error}=await db.from('notifications').insert({title:b.title,message:b.message,created_at:now()});if(error)throw error;let pushResult='stored';if(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY&&process.env.VAPID_SUBJECT){try{webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);const {data:subs}=await db.from('push_subscriptions').select('*');await Promise.all((subs||[]).map(x=>webpush.sendNotification({endpoint:x.endpoint,keys:{p256dh:x.p256dh,auth:x.auth}},JSON.stringify({title:b.title,body:b.message,url:'/'})).catch(()=>null)));pushResult='push-attempted'}catch(e){pushResult='push-error'}}res.json({ok:true,pushResult})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/push/subscribe',async(req,res)=>{try{const b=req.body||{};if(!b.endpoint)return res.status(400).json({error:'subscription required'});const {error}=await db.from('push_subscriptions').upsert({endpoint:b.endpoint,p256dh:b.keys?.p256dh||'',auth:b.keys?.auth||''},{onConflict:'endpoint'});if(error)throw error;res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/stats',async(req,res)=>{try{const [m,v,r,t,a]=await Promise.all([db.from('members').select('id',{count:'exact',head:true}),db.from('members').select('id',{count:'exact',head:true}).like('role','%कार्यकर्ता%'),db.from('receipts').select('id',{count:'exact',head:true}),db.from('receipts').select('amount'),(async()=>{const d=new Date().toISOString().slice(0,10);return db.from('aarti').select('*').eq('date',d).order('id',{ascending:true}).limit(1).maybeSingle()})()]);if(m.error||v.error||r.error||t.error||a.error)throw(m.error||v.error||r.error||t.error||a.error);const total=(t.data||[]).reduce((s,x)=>s+Number(x.amount||0),0);res.json({members:m.count||0,volunteers:v.count||0,receipts:r.count||0,total,aarti:a.data||null})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/export.csv',admin,async(req,res)=>{try{const {data,error}=await db.from('receipts').select('*').order('created_at',{ascending:false});if(error)throw error;const head='Receipt ID,Date,Name,Mobile,Amount,Payment,Address,Note\n';const esc=x=>'"'+String(x??'').replace(/"/g,'""')+'"';const csv=head+(data||[]).map(r=>[r.id,r.created_at,r.name,r.mobile,r.amount,r.payment,r.address,r.note].map(esc).join(',')).join('\n');res.setHeader('Content-Type','text/csv');res.setHeader('Content-Disposition','attachment; filename="srp-receipts-2027.csv"');res.send(csv)}catch(e){res.status(500).send(e.message)}});

module.exports=app;
