create table if not exists settings (k text primary key, v text default '');
create table if not exists members (id text primary key, name text not null, mobile text default '', email text default '', address text default '', role text default 'सदस्य', area text default '', photo text default '', created_at timestamptz not null default now());
create table if not exists receipts (id text primary key, name text, mobile text default '', address text default '', amount numeric not null, payment text default 'रोख', amount_words text default '', note text default '', created_at timestamptz not null default now(), member_id text default '');
create table if not exists aarti (id bigint generated by default as identity primary key, date date not null, time text default '', member_id text default '', member_name text default '', notes text default '');
create table if not exists notifications (id bigint generated by default as identity primary key, title text not null, message text not null, created_at timestamptz not null default now());
create table if not exists push_subscriptions (id bigint generated by default as identity primary key, endpoint text unique not null, p256dh text default '', auth text default '');
insert into settings(k,v) values ('upi',''),('contact',''),('address',''),('vapidPublicKey','') on conflict(k) do nothing;
-- This API uses the Supabase service-role key only on the server. Do not expose it in browser code.
